#!/usr/bin/env python3
"""Convert browser cookie export to Netscape format for yt-dlp"""

import sys
from pathlib import Path

def convert_to_netscape_format(input_file, output_file):
    """Convert custom cookie format to Netscape cookies.txt format"""
    
    # Read the malformed cookie file
    with open(input_file, 'r') as f:
        lines = f.readlines()
    
    # Write in Netscape format
    with open(output_file, 'w') as f:
        # Write header
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by fix_youtube_cookies.py\n\n")
        
        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
                
            # Parse the custom format
            parts = line.split('\t')
            if len(parts) < 7:
                continue
                
            try:
                # Extract fields from custom format
                name = parts[0].replace('→', '').strip()
                value = parts[1].strip()
                domain = parts[2].strip()
                path = parts[3].strip()
                # Skip expiry date parsing - use a far future date
                secure = 'TRUE' if '✓' in line else 'FALSE'
                
                # Skip empty names
                if not name:
                    continue
                
                # Netscape format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
                # Use 0 for session cookies, far future (2147483647) for persistent
                expiry = '2147483647'  # Year 2038
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                
                netscape_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n"
                f.write(netscape_line)
                
            except Exception as e:
                print(f"Skipping malformed line: {line[:50]}...")
                continue
    
    print(f"✅ Converted cookies saved to: {output_file}")
    print(f"📋 Total cookies processed: {len([l for l in lines if l.strip() and not l.startswith('#')])}")

if __name__ == "__main__":
    input_file = Path.home() / ".config/renaissance-weekly/cookies/youtube_cookies.txt"
    output_file = Path.home() / ".config/renaissance-weekly/cookies/youtube_cookies_fixed.txt"
    
    if not input_file.exists():
        print(f"❌ Cookie file not found: {input_file}")
        sys.exit(1)
    
    convert_to_netscape_format(input_file, output_file)
    print(f"\n🎯 Next steps:")
    print(f"1. mv {output_file} {input_file}")
    print(f"2. Run your download again")